version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Build genetic api image
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker image build -t dscythe/tmga-ga .
            docker push dscythe/tmga-ga

  deploy:
    machine: true
    steps:
      - checkout
      - run:
          name: Deploy to remote host
          command: |
            ssh centos@13.209.35.6 \
            "sudo docker pull dscythe/tmga-ga && \
            sudo docker container rm -f tmga_ga || true && \
            sudo docker container run \
            --rm -ditp 5000:9000 --name tmga_ga dscythe/tmga-ga"

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
